package jobaction

type AddUsersOrganizationAction string

const (
	ADD_USERS_ORGANIZATION_VALIDATE_ORGANIZATION AddUsersOrganizationAction = "VALIDATE_ORGANIZATION"
	ADD_USERS_ORGANIZATION_VALIDATE_USER         AddUsersOrganizationAction = "VALIDATE_USER"
	ADD_USERS_ORGANIZATION_ADD_ORGANIZATION_USER AddUsersOrganizationAction = "ADD_ORGANIZATION_USER"
	ADD_USERS_ORGANIZATION_ADD_DEFAULT_TEAM_USER AddUsersOrganizationAction = "ADD_DEFAULT_TEAM_USER"
)

type CreateOrganizationAction string

const (
	CREATE_ORGANIZATION_VALIDATE_ORGANIZATION CreateOrganizationAction = "VALIDATE_ORGANIZATION"
	CREATE_ORGANIZATION_VALIDATE_USER         CreateOrganizationAction = "VALIDATE_USER"
	CREATE_ORGANIZATION_CREATE_ORGANIZATION   CreateOrganizationAction = "CREATE_ORGANIZATION_AND_ADD_INITIAL_ORGANIZATION_USER"
	CREATE_ORGANIZATION_CREATE_DEFAULT_TEAM   CreateOrganizationAction = "CREATE_DEFAULT_TEAM_AND_ADD_INITIAL_DEFAULT_TEAM_USER"
)
